### ISSUE TITLE
About dependency installation

### ISSUE THREAD

**Issue by ButoneDream** [I2-Multimedia-Lab/CDFormer#1]
Thank you for open sourcing such great work 
however ， I noticed that there are nearly 400 dependent packages. When installing, I often encounter errors similar to the following: 
```
ERROR: Could not find a version that satisfies the requirement conda-repo-cli==1.0.4 (from versions: none)
ERROR: No matching distribution found for conda-repo-cli==1.0.4
```
My environment configuration is as follows:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Python 3.10.0
pytorch                   2.0.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
How can I quickly **solve environment configuration** problems?
I tried removing ==version but this doesn't always work。

**Comment by nsqg** [comment]
Thanks for your interest in this work, we have updated the requirements.txt to ensure the environment can be reproduced.

**Comment by ButoneDream** [comment]
thanks for the reply
If I want to use my own test image set, which parameters in `option_x2.py`  should be adjusted? Can you provide more specific guidance?

**Comment by nsqg** [comment]
We have re-updated the code to test any data set, and you can download the new code. Change `data_test` to `FreeData` in `option_x2.py` and put your images in `data/benchmark/FreeData/HR`.
