### ISSUE TITLE
Test时为什么将HR也输入给Model？

### ISSUE THREAD

**Issue by para999** [I2-Multimedia-Lab/CDFormer#13]
您好，在复现您的模型时遇到了一些问题。请问Test时为什么将HR也输入给Model，在测试时HR不是应该仅用于计算PSNR等指标吗，将HR输入网络用于获取SR重建结果是出于什么原因呢？期待您的答复

**Comment by 2402227288** [comment]
难绷

**Comment by ShuimuChen-hyq** [comment]
答复了吗，我也有疑问

**Comment by bokeyyy** [comment]
源码中test时将hr输入到模型中但是并没有使用，因为diffusion标识为true并且模型是测试模式，forward只运行了           
下面这段代码
                cdp_diff = self.netG(img)    
                sr = self.SR(img, cdp_diff)
